In [1]:
import pandas as pd
import xlwings as xw
import numpy as np
from keplergl import KeplerGl as kp
import pytz
import json
import seaborn as sns
import requests as re
import time
import json

In [2]:
#import dataframes
path1= '/Users/jacklobe/lighthouse/Final/Ruter_Nov2019_Sep2020.csv'
path2= '/Users/jacklobe/lighthouse/Final/ StarTran_Apr2020_Sep2020.csv'
path3= '/Users/jacklobe/lighthouse/Final/DART_Jan2019_Sep2020.csv'
path4= '/Users/jacklobe/lighthouse/Final/SouthwestTransit_Aug2019_Sep2020.csv'
#################
rueter=pd.read_csv(path1)
StarTran=pd.read_csv(path2)
dart=pd.read_csv(path3)
swtran=pd.read_csv(path4)

In [3]:
micro_census=pd.read_excel('/Users/jacklobe/lighthouse/Final/CensusData_MicrotransitDemandParameters_CBG_2016.xlsx')
para_census=pd.read_excel('/Users/jacklobe/lighthouse/Final/CensusData_ParatransitDemandParameters_CBG_2016.xlsx')

In [4]:
para_census

,CBG,TotalPop,TotalPovertyStatusAssessed,BelowPovertyAndDisabled,ProportionPoorAndDisabled,ProportionOfZeroCarHouseholds,ProportionBelowPovertyLevel,ProportionSeniors,TotalMalePop,MalePop65_67,...,MalePop75_79,MalePop80_84,MalePop85+,TotalFemalePop,FemalePop65_67,FemalePop67_69,FemlePop70_74,FemalePop75_79,FemalePop80_84,FemalePop85+
0,10010201001,745,511,6,1.174168,3.873239,19.194631,3.624161,356,0,...,0,0,0,389,0,5,7,5,0,0
1,10010201002,1265,820,4,0.487805,0.877193,4.426877,11.462451,639,10,...,4,11,0,626,11,25,23,12,6,0
2,10010202001,960,509,36,7.072692,10.880829,38.219895,16.145833,534,7,...,25,0,0,426,10,28,17,20,24,10
3,10010202002,1236,698,28,4.011461,11.061947,11.142587,9.466019,634,4,...,9,0,0,602,28,9,10,8,17,18
4,10010203001,2364,1426,46,3.225806,0.728155,4.230118,13.409475,1125,8,...,41,0,0,1239,4,58,44,40,26,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220328,721537506011,921,519,187,36.030829,23.571429,67.535288,22.692725,460,13,...,0,0,0,461,48,32,25,0,19,22
220329,721537506012,2703,1729,62,3.585888,7.914764,43.581206,10.765816,1353,14,...,24,0,25,1350,59,20,15,38,53,8
220330,721537506013,1195,723,97,13.416321,0.000000,24.435146,5.774059,583,9,...,0,0,0,612,9,0,21,0,0,9
220331,721537506021,2005,1238,329,26.575121,17.989418,72.613065,22.044888,926,0,...,35,14,8,1079,94,46,63,31,25,8
220332,721537506022,736,381,68,17.847769,18.483412,81.250000,44.157609,279,78,...,0,56,0,457,13,9,44,25,0,50

In [5]:
companies=rueter,StarTran,dart,swtran

In [6]:
def checkmissing(data):
    total = data.isnull().sum().sort_values(ascending=False)
    percent = (data.isnull().sum()/data.isnull().count()).sort_values(ascending=False)
    missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
    return missing_data.head(len(data.columns))

## General missing values filling etc (wow there are none!)

In [7]:
checkmissing(rueter)

                             Total  Percent
endpoint                         0      0.0
travelDuration                   0      0.0
travelDistance                   0      0.0
statusChanges                    0      0.0
status                           0      0.0
serviceId                        0      0.0
requestedDropoffLongitude        0      0.0
requestedDropoffLatitude         0      0.0
requestedPickupLongitude         0      0.0
requestedPickupLatitude          0      0.0
requestedDropoffTsTimestamp      0      0.0
requestedPickupTsTimestamp       0      0.0
requestedDropoffTs               0      0.0
requestedPickupTs                0      0.0

In [8]:
checkmissing(StarTran)

                             Total  Percent
endpoint                         0      0.0
travelDuration                   0      0.0
travelDistance                   0      0.0
statusChanges                    0      0.0
status                           0      0.0
serviceId                        0      0.0
requestedDropoffLongitude        0      0.0
requestedDropoffLatitude         0      0.0
requestedPickupLongitude         0      0.0
requestedPickupLatitude          0      0.0
requestedDropoffTsTimestamp      0      0.0
requestedPickupTsTimestamp       0      0.0
requestedDropoffTs               0      0.0
requestedPickupTs                0      0.0

In [9]:
checkmissing(dart)

                             Total  Percent
endpoint                         0      0.0
travelDuration                   0      0.0
travelDistance                   0      0.0
statusChanges                    0      0.0
status                           0      0.0
serviceId                        0      0.0
requestedDropoffLongitude        0      0.0
requestedDropoffLatitude         0      0.0
requestedPickupLongitude         0      0.0
requestedPickupLatitude          0      0.0
requestedDropoffTsTimestamp      0      0.0
requestedPickupTsTimestamp       0      0.0
requestedDropoffTs               0      0.0
requestedPickupTs                0      0.0

In [10]:
checkmissing(swtran)

                             Total  Percent
endpoint                         0      0.0
travelDuration                   0      0.0
travelDistance                   0      0.0
statusChanges                    0      0.0
status                           0      0.0
serviceId                        0      0.0
requestedDropoffLongitude        0      0.0
requestedDropoffLatitude         0      0.0
requestedPickupLongitude         0      0.0
requestedPickupLatitude          0      0.0
requestedDropoffTsTimestamp      0      0.0
requestedPickupTsTimestamp       0      0.0
requestedDropoffTs               0      0.0
requestedPickupTs                0      0.0

# General EDA to explore what each column means, ecoding it to proper time etc

In [11]:
#each df will have endpoint with various types 
for i in companies:
    print (i.endpoint.unique())
#note scheduled means they were scheduled, nextAvailable means that it was called, not planned
#flagDown means that it was instant 
#We will want to explore the differences between these endpoints

['scheduled' 'nextAvailable' 'flagDown']
['nextAvailable' 'scheduled' 'flagDown']
['nextAvailable' 'scheduled' 'flagDown']
['nextAvailable' 'flagDown' 'scheduled']

In [12]:
swtran

,requestedPickupTs,requestedDropoffTs,requestedPickupTsTimestamp,requestedDropoffTsTimestamp,requestedPickupLatitude,requestedPickupLongitude,requestedDropoffLatitude,requestedDropoffLongitude,serviceId,status,statusChanges,travelDistance,travelDuration,endpoint
0,1567108735,1567109213,2019-08-29T19:58:55Z,2019-08-29T20:06:53Z,44.796685,-93.586401,44.832909,-93.568735,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567108736, ""status"": ""processing""}, {...",4895,478,nextAvailable
1,1567108880,1567109429,2019-08-29T20:01:20Z,2019-08-29T20:10:29Z,44.853806,-93.419128,44.825236,-93.427182,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567108880, ""status"": ""processing""}, {...",4310,549,nextAvailable
2,1567109218,1567110149,2019-08-29T20:06:58Z,2019-08-29T20:22:29Z,44.862814,-93.522557,44.817545,-93.617486,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567109218, ""status"": ""processing""}, {...",11385,931,nextAvailable
3,1567109350,1567110072,2019-08-29T20:09:10Z,2019-08-29T20:21:12Z,44.851744,-93.588388,44.806882,-93.590702,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567109350, ""status"": ""processing""}, {...",8422,722,nextAvailable
4,1567109476,1567110753,2019-08-29T20:11:16Z,2019-08-29T20:32:33Z,44.851223,-93.421839,44.793831,-93.590504,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567109476, ""status"": ""processing""}, {...",21483,1277,nextAvailable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82114,1567107159,1567108105,2019-08-29T19:32:39Z,2019-08-29T19:48:25Z,44.876525,-93.408421,44.864018,-93.573141,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567107159, ""status"": ""processing""}, {...",16110,946,nextAvailable
82115,1567107473,1567108157,2019-08-29T19:37:53Z,2019-08-29T19:49:17Z,44.757576,-93.638411,44.779675,-93.651632,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567107475, ""status"": ""processing""}, {...",4186,684,nextAvailable
82116,1567107522,1567107935,2019-08-29T19:38:42Z,2019-08-29T19:45:35Z,44.835539,-93.443745,44.860004,-93.443051,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567107522, ""status"": ""processing""}, {...",4257,413,nextAvailable
82117,1567108004,1567108706,2019-08-29T19:46:44Z,2019-08-29T19:58:26Z,44.845743,-93.423709,44.872477,-93.490840,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567108004, ""status"": ""processing""}, {...",7848,702,nextAvailable
82118,1567108101,1567108863,2019-08-29T19:48:21Z,2019-08-29T20:01:03Z,44.860498,-93.445359,44.889889,-93.522638,089fdbc8-ef59-4f15-a169-f9ae78818ece,cancelled,"[{""ts"": 1567108101, ""status"": ""processing""}, {...",10650,762,nextAvailable

In [4]:
swtran

,requestedPickupTs,requestedDropoffTs,requestedPickupTsTimestamp,requestedDropoffTsTimestamp,requestedPickupLatitude,requestedPickupLongitude,requestedDropoffLatitude,requestedDropoffLongitude,serviceId,status,statusChanges,travelDistance,travelDuration,endpoint
0,1567108735,1567109213,2019-08-29T19:58:55Z,2019-08-29T20:06:53Z,44.796685,-93.586401,44.832909,-93.568735,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567108736, ""status"": ""processing""}, {...",4895,478,nextAvailable
1,1567108880,1567109429,2019-08-29T20:01:20Z,2019-08-29T20:10:29Z,44.853806,-93.419128,44.825236,-93.427182,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567108880, ""status"": ""processing""}, {...",4310,549,nextAvailable
2,1567109218,1567110149,2019-08-29T20:06:58Z,2019-08-29T20:22:29Z,44.862814,-93.522557,44.817545,-93.617486,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567109218, ""status"": ""processing""}, {...",11385,931,nextAvailable
3,1567109350,1567110072,2019-08-29T20:09:10Z,2019-08-29T20:21:12Z,44.851744,-93.588388,44.806882,-93.590702,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567109350, ""status"": ""processing""}, {...",8422,722,nextAvailable
4,1567109476,1567110753,2019-08-29T20:11:16Z,2019-08-29T20:32:33Z,44.851223,-93.421839,44.793831,-93.590504,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567109476, ""status"": ""processing""}, {...",21483,1277,nextAvailable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82114,1567107159,1567108105,2019-08-29T19:32:39Z,2019-08-29T19:48:25Z,44.876525,-93.408421,44.864018,-93.573141,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567107159, ""status"": ""processing""}, {...",16110,946,nextAvailable
82115,1567107473,1567108157,2019-08-29T19:37:53Z,2019-08-29T19:49:17Z,44.757576,-93.638411,44.779675,-93.651632,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567107475, ""status"": ""processing""}, {...",4186,684,nextAvailable
82116,1567107522,1567107935,2019-08-29T19:38:42Z,2019-08-29T19:45:35Z,44.835539,-93.443745,44.860004,-93.443051,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567107522, ""status"": ""processing""}, {...",4257,413,nextAvailable
82117,1567108004,1567108706,2019-08-29T19:46:44Z,2019-08-29T19:58:26Z,44.845743,-93.423709,44.872477,-93.490840,089fdbc8-ef59-4f15-a169-f9ae78818ece,completed,"[{""ts"": 1567108004, ""status"": ""processing""}, {...",7848,702,nextAvailable
82118,1567108101,1567108863,2019-08-29T19:48:21Z,2019-08-29T20:01:03Z,44.860498,-93.445359,44.889889,-93.522638,089fdbc8-ef59-4f15-a169-f9ae78818ece,cancelled,"[{""ts"": 1567108101, ""status"": ""processing""}, {...",10650,762,nextAvailable

In [5]:
#now we have companies in zulu time they need to be converted to local time 
#rueter is in Oslo Norway Europe/Oslo
#StarTran is in Lincon Nebraska  US/Central
#dart is in Dallas, Texas US/Central
#swtran is in Minneaplois Minnisota US/Central

In [6]:
central=StarTran, dart, swtran

In [7]:
def convertcentral(data):
    #converts central timezones to pandas datetime and converts it to central time
    data['requestedPickupTs'] = pd.DatetimeIndex(pd.to_datetime(data['requestedPickupTs'],unit='s')).tz_localize('UTC').tz_convert('US/Central').tz_convert(None)
    data['requestedDropoffTs'] = pd.DatetimeIndex(pd.to_datetime(data['requestedDropoffTs'],unit='s')).tz_localize('UTC').tz_convert('US/Central').tz_convert(None)
    return data

In [8]:
for i in central:
    convertcentral(i)

In [9]:
#converts reuter data to Oslo time 
rueter['requestedPickupTs'] = pd.DatetimeIndex(pd.to_datetime(rueter['requestedPickupTs'],unit='s')).tz_localize('UTC').tz_convert('Europe/Oslo').tz_convert(None)
rueter['requestedDropoffTs'] = pd.DatetimeIndex(pd.to_datetime(rueter['requestedDropoffTs'],unit='s')).tz_localize('UTC').tz_convert('Europe/Oslo').tz_convert(None)

In [10]:
#hold off on dropping timestamps until we talk to jerome, also concerned about actual functionality of loop need to 
#find a way to check results 
#status accepted and status inProgress

In [11]:
import ast
from pandas import json_normalize

def only_dict(d):
    '''
    Convert json string representation of dictionary to a python dict
    '''
    return ast.literal_eval(d)

def list_of_dicts(ld):
    '''
    Create a mapping of the tuples formed after 
    converting json strings of list to a python list   
    '''
    return dict([(list(d.values())[1], list(d.values())[0]) for d in ast.literal_eval(ld)])

In [12]:
B=json_normalize(rueter['statusChanges'].apply(list_of_dicts).tolist())
rueter=rueter.join(B)
B=json_normalize(StarTran['statusChanges'].apply(list_of_dicts).tolist())
StarTran=StarTran.join(B)
B=json_normalize(dart['statusChanges'].apply(list_of_dicts).tolist())
dart=dart.join(B)
B=json_normalize(swtran['statusChanges'].apply(list_of_dicts).tolist())
swtran=swtran.join(B)

In [13]:
metrics=['processing','accepted','arriving','inProgress','completed','cancelled','noDriversAvailable','serviceDisruption']

In [14]:
companies=StarTran,dart,swtran

In [15]:
for i in metrics:
    for j in companies:
        j[i]=pd.DatetimeIndex(pd.to_datetime(j[i],unit='s')).tz_localize('UTC').tz_convert('US/Central').tz_convert(None)

In [16]:
 for i in metrics:
        rueter[i] = pd.DatetimeIndex(pd.to_datetime(rueter[i],unit='s')).tz_localize('UTC').tz_convert('Europe/Oslo').tz_convert(None)

In [17]:
allcomp=StarTran,dart,swtran,rueter

In [18]:
#take times for waiting, no use for endpoints other then next available
for i in allcomp:
    i['Difference']=i['inProgress']-i['accepted']
    i['Difference'] = i['Difference'] / np.timedelta64(1, 'm')

In [19]:
j=dart.sample(n=2000, random_state=42)

In [20]:
def CBG(row):
    #get FIPS codes for each lat long within the data table 
    time.sleep(3)
    response=re.get(f'https://geo.fcc.gov/api/census/block/find?latitude={row["requestedPickupLatitude"]}&longitude={row["requestedPickupLongitude"]}&format=json').json()
    try:
        return response['Block']['FIPS']
    except:
        return 'error'

In [ ]:
#attach the fips codes to the df's for us countries
j['CBG']=j.apply(lambda row:CBG(row),axis=1)

In [ ]:
#delete fips codes to only 12 digits
j['CBG'] = j['CBG'].astype(str).str[:12]

In [9]:
miniswtran=swtran.sample(n=1000)
ministar=StarTran.sample(n=1000)

In [16]:
ministar['CBG']=ministar.apply(lambda row:CBG(row),axis=1)
ministar['CBG'] = ministar['CBG'].astype(str).str[:12]

In [17]:
miniswtran['CBG']=miniswtran.apply(lambda row:CBG(row),axis=1)
miniswtran['CBG'] = miniswtran['CBG'].astype(str).str[:12]

In [57]:
j.CBG=j.CBG.astype(int)

In [58]:
j=j.merge(micro_census,left_on='CBG', right_on='CBG')

In [24]:
#join census data based off of FIPS codes 
#dart=dart.merge(micro_census,left_on='CBG', right_on='CBG')
ministar.CBG=ministar.CBG.astype(int)
miniswtran.CBG=miniswtran.CBG.astype(int)
ministar=ministar.merge(para_census,left_on='CBG', right_on='CBG')
miniswtran=miniswtran.merge(micro_census,left_on='CBG', right_on='CBG')

In [ ]:
# miniswtran.to_csv('/Users/jacklobe/lighthouse/Final/swcensus')
# ministar.to_csv('/Users/jacklobe/lighthouse/Final/Starcensus')
#dart.to_csv('/Users/jacklobe/lighthouse/Final/dartcensus')

In [61]:
#j.to_csv('/Users/jacklobe/lighthouse/Final/small_dart_sample.csv')

#lambda funciton to remove datetime after 18

In [25]:
ministar.to_csv('/Users/jacklobe/lighthouse/Final/small_StarTran_sample.csv')
miniswtran.to_csv('/Users/jacklobe/lighthouse/Final/small_swtran_sample.csv')

,requestedPickupTs,requestedDropoffTs,requestedPickupTsTimestamp,requestedDropoffTsTimestamp,requestedPickupLatitude,requestedPickupLongitude,requestedDropoffLatitude,requestedDropoffLongitude,serviceId,status,...,MalePop75_79,MalePop80_84,MalePop85+,TotalFemalePop,FemalePop65_67,FemalePop67_69,FemlePop70_74,FemalePop75_79,FemalePop80_84,FemalePop85+
0,1592934300,1592935137,2020-06-23T17:45:00Z,2020-06-23T17:58:57Z,40.808380,-96.696437,40.858260,-96.677804,2329a3e8-a8bd-408a-829c-f409699e6b24,completed,...,0,0,33,105,21,0,0,0,10,0
1,1596467700,1596468891,2020-08-03T15:15:00Z,2020-08-03T15:34:51Z,40.808380,-96.696437,40.741263,-96.675073,2329a3e8-a8bd-408a-829c-f409699e6b24,completed,...,0,0,33,105,21,0,0,0,10,0
2,1596564900,1596566021,2020-08-04T18:15:00Z,2020-08-04T18:33:41Z,40.808380,-96.696437,40.825605,-96.606690,2329a3e8-a8bd-408a-829c-f409699e6b24,completed,...,0,0,33,105,21,0,0,0,10,0
3,1591469100,1591469654,2020-06-06T18:45:00Z,2020-06-06T18:54:14Z,40.808380,-96.696437,40.814561,-96.650706,2329a3e8-a8bd-408a-829c-f409699e6b24,completed,...,0,0,33,105,21,0,0,0,10,0
4,1598285064,1598285958,2020-08-24T16:04:24Z,2020-08-24T16:19:18Z,40.808380,-96.696437,40.812909,-96.608981,2329a3e8-a8bd-408a-829c-f409699e6b24,completed,...,0,0,33,105,21,0,0,0,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1591628526,1591628820,2020-06-08T15:02:06Z,2020-06-08T15:07:00Z,40.805772,-96.626007,40.805889,-96.625903,1cb4005e-3c68-4f88-820b-f651df75c7d7,completed,...,77,43,38,825,17,17,27,55,61,125
996,1589904606,1589905611,2020-05-19T16:10:06Z,2020-05-19T16:26:51Z,40.801012,-96.689007,40.868159,-96.671066,1cb4005e-3c68-4f88-820b-f651df75c7d7,completed,...,0,5,0,648,0,0,38,5,0,9
997,1600287300,1600288167,2020-09-16T20:15:00Z,2020-09-16T20:29:27Z,40.796142,-96.704774,40.782487,-96.622438,2329a3e8-a8bd-408a-829c-f409699e6b24,completed,...,0,0,0,518,0,0,0,0,0,0
998,1590085800,1590086877,2020-05-21T18:30:00Z,2020-05-21T18:47:57Z,40.783853,-96.626149,40.838936,-96.652036,2329a3e8-a8bd-408a-829c-f409699e6b24,completed,...,120,4,26,1194,0,74,63,83,109,142
999,1600692300,1600693133,2020-09-21T12:45:00Z,2020-09-21T12:58:53Z,40.814706,-96.672586,40.867916,-96.636490,2329a3e8-a8bd-408a-829c-f409699e6b24,completed,...,12,0,13,595,0,31,25,0,10,0

In [ ]:
#demand forcasting 
#time series/LSTMS demand forcasting 4
#ride time predictor

#requested transit, i am sitting at main and science world, who will get my ride? Who's my nearest driver? faster driver turnover

#to do this match location and pickup time and next puckup location ###removing operational bottleneck #stay in hot area
#identify what areas are specific to spare