In [1]:
import geopandas as gpd
import pandas as pd 
import keplergl

In [2]:
import pandas as pd

In [3]:
dallas_base = gpd.read_file('Census_Block_Group_2010_TX.geojson')

In [4]:
dallas_clusters=pd.read_csv('/Users/jacklobe/lighthouse/Final/clustered_CSV/dallas_kmeans.csv')

In [5]:
dallas_bus=pd.read_csv('dallas_transitmap.csv')

In [6]:
from keplergl import KeplerGl 
map_1 = KeplerGl(height=500)
map_1

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

KeplerGl(height=500)

In [7]:
map_1.add_data(data=dallas_base, name='basemap')

In [ ]:
map_1.add_data(data=dallas_clusters,name='clusters')
map_1.add_data(data=dallas_bus,name='routes')

In [ ]:
map_1.save_to_html(file_name='kepler_clustered_dallas.html')

In [ ]:
swtran_cluster=pd.read_csv('clustered_CSV/swtran_clusters.csv')
swtran_race=pd.read_csv('racial_swtran.csv')

In [ ]:
map_2 = KeplerGl(height=500)
map_2.add_data(data=swtran_cluster, name='sw_clusters')
map_2.add_data(data=swtran_race,name='sw_race')

In [ ]:
map_2.save_to_html(file_name='kepler_clustered_swtran.html')

In [ ]:
map_2

In [5]:
dallas_clusters

,Unnamed: 0,Unnamed: 0.1,requestedPickupTs,requestedDropoffTs,requestedPickupLatitude,requestedPickupLongitude,requestedDropoffLatitude,requestedDropoffLongitude,serviceId,status,...,completed,cancelled,noDriversAvailable,serviceDisruption,Prop_Black,Prop_White,Prop_Hispanic,Prop_Asian,Difference,clusters
0,0,0,2020-04-21 17:34:19,2020-04-21 17:47:10,32.931741,-96.525914,32.904062,-96.564146,d0a57efd-e2cc-4a03-9ae6-fef917a74b76,completed,...,2020-04-21 18:04:27,NaN,NaN,NaN,0.162095,0.585723,0.144638,0.064838,14.683333,2
1,1,44,2019-09-23 13:00:00,2019-09-23 13:05:31,32.934094,-96.525330,32.916508,-96.521620,d0a57efd-e2cc-4a03-9ae6-fef917a74b76,completed,...,NaN,2020-03-09 19:00:59,NaN,NaN,0.162095,0.585723,0.144638,0.064838,NaN,2
2,2,52,2019-08-06 21:30:00,2019-08-06 21:42:55,32.936103,-96.530935,32.904062,-96.564146,d0a57efd-e2cc-4a03-9ae6-fef917a74b76,completed,...,NaN,2019-05-08 02:29:54,NaN,NaN,0.162095,0.585723,0.144638,0.064838,NaN,2
3,3,59,2019-04-03 11:28:17,2019-04-03 11:37:48,32.930262,-96.521496,32.904062,-96.564146,d0a57efd-e2cc-4a03-9ae6-fef917a74b76,completed,...,NaN,2020-04-24 15:59:18,NaN,NaN,0.162095,0.585723,0.144638,0.064838,NaN,2
4,4,65,2019-04-03 11:56:11,2019-04-03 12:07:04,32.945021,-96.527977,32.904128,-96.563448,d0a57efd-e2cc-4a03-9ae6-fef917a74b76,cancelled,...,2020-05-15 16:02:13,NaN,NaN,NaN,0.162095,0.585723,0.144638,0.064838,26.166667,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272037,272037,237278,2019-07-24 12:13:51,2019-07-24 12:18:45,32.698255,-96.682956,32.718598,-96.685063,d05800ea-93bc-4e14-ae3b-419fee0a80a2,completed,...,2019-05-03 14:32:04,NaN,NaN,NaN,0.057836,0.332090,0.769279,0.006219,174.916667,5
272038,272038,184398,2019-04-11 17:52:12,2019-04-11 18:03:03,32.842825,-96.691072,32.855763,-96.732869,d41799c0-2f24-4a22-a5d4-6b776aa7c949,cancelled,...,NaN,2019-04-15 22:06:00,NaN,NaN,0.107454,0.545015,0.384318,0.014521,NaN,4
272039,272039,193418,2019-01-23 03:56:00,2019-01-23 04:22:16,32.899800,-97.040300,32.900430,-97.173350,bc5bd214-d4ca-41fb-a6ef-9c5c412e7206,completed,...,2020-01-22 15:06:52,NaN,NaN,NaN,0.000000,0.066667,0.933333,0.000000,11.400000,4
272040,272040,241270,2019-05-07 18:43:00,2019-05-07 19:00:14,33.099242,-96.733344,33.033556,-96.701109,1e995f05-cd00-4f9c-86a7-84e8867ee42d,completed,...,2019-04-01 22:09:37,NaN,NaN,NaN,0.065802,0.497220,0.091752,0.328545,5727.383333,0
272041,272041,262563,2019-11-25 18:26:58,2019-11-25 18:34:16,32.850174,-96.773846,32.900327,-96.768636,671bf16c-0ff1-4841-9795-1644d57bd56c,cancelled,...,2019-03-13 19:23:38,NaN,NaN,NaN,0.000000,0.819266,0.048624,0.031193,22.316667,4